---
#Configuracion del Servidor
enableLoggingRequestDetails: false
server:
  error:
    include-message: always
    include-binding-errors: always
#Configuracion del log
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    dateformat: HH:mm:ss
spring:
  main:
    #Quitar banner de Spring
    banner-mode: off
  #Base de datos
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/example?createDatabaseIfNotExist=true
    username: ${DB_USER}
    tomcat:
      max-wait: 280000
      max-active: 50
      max-idle: 20
      min-idle: 15
  #Aclaraciones para JPA
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #Configuraciones de email
  mail:
    username: marcoslopezdev18@gmail.com
...