spring:
  main:
    banner-mode: off
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/prueba
    username: root
  driver-class-name: com.mysql.cj.jdbc.Driver
  tomcat:
    max-wait: 280000
    max-active: 50
    max-idle: 20
    min-idle: 15
  #Aclaraciones para JPA
  jpa:
    #Lenguaje
    database: MYSQL
    #Dialecto
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
